title: FatManDJ
subtitle: hello world!
subscription: 一个小学生
name: James Jiang
# WARN:Don't Open Debug Mode When You Deploy It On A PC!
#link
#Need to be a full link
blog: https://blog.fatdev.name
zhihu: https://zhihu.com
github: https://github.com/JiangYuShuo10023
#theme
theme: covquicked
